apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-mcp-chat
  title: '@internal/mcp-chat'
  description: >-
    A Backstage plugin that provides a chat interface for interacting with the
    MCP Servers.
spec:
  lifecycle: experimental
  type: backstage-workspace
  owner: '@Lucifergene'
