apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-stack-overflow
  title: '@internal/stack-overflow'
spec:
  lifecycle: experimental
  type: backstage-workspace
  owner: '@backstage/community-plugins-maintainers'
