apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-confluence
  title: '@internal/confluence'
spec:
  lifecycle: experimental
  type: backstage-workspace
  owner: '@fjudith'
