apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-scaffolder-backend-module-sonarqube
  title: '@internal/scaffolder-backend-module-sonarqube'
spec:
  lifecycle: experimental
  type: backstage-workspace
  owner: '@AndrienkoAleksandr'
