apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-keycloak
  title: '@internal/keycloak'
spec:
  lifecycle: experimental
  type: backstage-workspace
  owner: '@AndrienkoAleksandr'
