apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-multi-source-security-viewer
  title: '@internal/multi-source-security-viewer'
spec:
  lifecycle: experimental
  type: backstage-workspace
  owner: '@caugello'
