apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-apache-airflow
  title: '@internal/apache-airflow'
spec:
  lifecycle: experimental
  type: backstage-workspace
  owner: '@backstage/community-plugins-maintainers'
