apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-azure-sites
  title: '@internal/azure-sites'
spec:
  lifecycle: experimental
  type: backstage-workspace
  owner: '@deepan10'
