apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-servicenow
  title: '@internal/servicenow'
spec:
  lifecycle: experimental
  type: backstage-workspace
  owner: '@AndrienkoAleksandr'
