apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-github-pull-requests-board
  title: '@internal/github-pull-requests-board'
spec:
  lifecycle: experimental
  type: backstage-workspace
  owner: '@gregorytalita'
